stages:
  - build
  - deploy

image: docker
services:
  - docker:dind
variables:
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo -n $password | docker login -u $user --password-stdin localhost:9001

build:
  only:
    - main
  stage: build
  script:
    - docker build . --tag localhost:9001/cicd-example:latest
    - docker push localhost:9001/cicd-example:latest
  tags:
    - build

deploy:
  only:
    - main
  stage: deploy
  script:
    - docker rm -f cicd-example
    - docker run -d --name cicd-example -p 3000:3000 localhost:9001/cicd-example:latest
  tags:
    - deploy